name = "AcceleratedDCPowerFlows"
uuid = "c32744f1-403b-4af7-9195-1da907387c09"
version = "0.1.0"
authors = ["mtanneau3 <mtanneau3@gatech.edu>"]

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"

[extensions]
CUDAExt = ["CUDA", "CUDSS"]

[compat]
CUDA = "5.9.6"
CUDSS = "0.6.6"
KLU = "0.6.0"
MetaGraphsNext = "0.8.0"
